# =============================================================================
# web-rstk-dev - Heroku Application
# =============================================================================
# Part of the "web" pipeline, "development" stage.
# Mirrors the live Heroku app. Shared logic and common defaults live in the
# rstk-app module; only this app's specifics are set below.
#
# Generated by tools/codify_app.py - safe to edit by hand afterwards.
# =============================================================================

module "app" {
  source = "../../../../modules/rstk-app"

  app_name      = "web-rstk-dev"
  pipeline_name = "web"
  # pipeline_stage defaults to "development"

  # No GitHub integration is configured on this app (github_repo stays null,
  # which skips the Kolkrabbi wiring in the module).

  # Add-ons owned by this app
  addons = {
    cloudamqp  = "cloudamqp:squirrel-1"
    papertrail = "papertrail:choklad"
  }

  # Dyno formation (live values)
  formations = {
    web = { size = "standard-1x", quantity = 1 }
  }

  # Non-sensitive config vars. DEFAULT_MONGODB=ORMONGO comes from the module base.
  config_vars = {
    APPS_REDIRECT_URL            = "https://web-rstk-dev.herokuapp.com/sf/oauth/callback"
    BOTH_MONGOS                  = "false"
    CAPTURE_REQUEST_RATE         = "true"
    CATG_LARGE_ORGS              = "00D36000001Ee5MEAS"
    ENABLE_STORE_REQUEST_FEATURE = "TRUE"
    LOG_LEVEL                    = "DEBUG"
    "MRP_VERSIONS_LAST-3"        = "19.20-23.93"
    NO_NAMESPACE_ORGS            = "00DU00000"
    ORMONGO_ORGS                 = ""
    QNAME_B4TICKET_ROOTF         = "CURR"
    REQ_THRESHOLD_LARGE          = "25"
    "ROOTF_VERSIONS_LAST-0"      = "1.19-1.25"
    SFORCE_REDIRECT_URL          = "https://web-rstk-dev.herokuapp.com/sf/oauth/callback"
    SRC_ORG_QNAME                = "CURR"
    STORE_LEAST_NO_OF_PARMS      = "TRUE"
    THRESHOLD_TIME_IN_SECS       = "60"
    USE_OLDER_IMPL               = "FALSE"
  }

  # Sensitive config vars - values come from the `secrets` map supplied via
  # terraform.tfvars (gitignored). Explicit lookups so a missing key fails
  # loudly at plan time instead of silently dropping a config var.
  sensitive_config_vars = {
    APPS_CLIENT_KEY      = var.secrets["APPS_CLIENT_KEY"]
    APPS_CLIENT_SECRET   = var.secrets["APPS_CLIENT_SECRET"]
    MONGOLAB_URI         = var.secrets["MONGOLAB_URI"]
    ORMONGO_DBNAME       = var.secrets["ORMONGO_DBNAME"]
    ORMONGO_PASSWORD     = var.secrets["ORMONGO_PASSWORD"]
    ORMONGO_USERNAME     = var.secrets["ORMONGO_USERNAME"]
    RSTK_KEY             = var.secrets["RSTK_KEY"]
    SFORCE_CLIENT_KEY    = var.secrets["SFORCE_CLIENT_KEY"]
    SFORCE_CLIENT_SECRET = var.secrets["SFORCE_CLIENT_SECRET"]
    devqaff_dbname       = var.secrets["devqaff_dbname"]
    pde3_dbname          = var.secrets["pde3_dbname"]
    pde3f_dbname         = var.secrets["pde3f_dbname"]
    pde5_dbname          = var.secrets["pde5_dbname"]
    pde5f_dbname         = var.secrets["pde5f_dbname"]
    qarsf_dbname         = var.secrets["qarsf_dbname"]
  }
}

# -----------------------------------------------------------------------------
# Addon-injected config vars (NOT managed here)
# -----------------------------------------------------------------------------
# These are set automatically by the attached add-ons, so they are intentionally
# absent from the config above:
#   - CLOUDAMQP_APIKEY      -> cloudamqp (owned by this app)
#   - CLOUDAMQP_URL         -> cloudamqp (owned by this app)
#   - DATABASE_URL          -> heroku-postgresql (billed to mrp-rstk-prod)
#   - ORMONGO_REGION        -> ormongo (billed to worker-rstk-dev)
#   - ORMONGO_RS_URL        -> ormongo (billed to worker-rstk-dev)
#   - ORMONGO_URL           -> ormongo (billed to worker-rstk-dev)
#   - PAPERTRAIL_API_TOKEN  -> papertrail (owned by this app)

# -----------------------------------------------------------------------------
# Shared add-ons attached to this app (billed to OTHER apps - not managed here)
# -----------------------------------------------------------------------------
#   - heroku-postgresql:standard-2  (billed to mrp-rstk-prod)
#   - ormongo:2-mmap  (billed to worker-rstk-dev)
