# =============================================================================
# worker-qa-last-0 - Heroku Application
# =============================================================================
# Part of the "worker" pipeline, "staging" stage.
# Mirrors the live Heroku app. Shared logic and common defaults live in the
# rstk-app module; only this app's specifics are set below.
#
# Generated by tools/codify_app.py - safe to edit by hand afterwards.
# =============================================================================

module "app" {
  source = "../../../../modules/rstk-app"

  app_name       = "worker-qa-last-0"
  pipeline_name  = "worker"
  pipeline_stage = "staging"
  stack          = "heroku-22" # differs from the module default

  # No GitHub integration is configured on this app (github_repo stays null,
  # which skips the Kolkrabbi wiring in the module).

  # This app owns no add-ons
  addons = {}

  # Dyno formation (live values)
  formations = {
    worker = { size = "standard-1x", quantity = 1 }
  }

  # Non-sensitive config vars. DEFAULT_MONGODB=ORMONGO comes from the module base.
  config_vars = {
    QUEUE_NAME                                = "LAST-0"
    RF_APP_NAME                               = "rootf-qa-last-0"
    RF_ONEOFF_DYNO_TYPE                       = "standard-2x"
    RF_PROCFILE_PROCESS_NAME                  = "rfworker"
    SFORCE_NAMESPACE                          = "DOX__"
    qarsf_sb_erp_mrp_APP_NAME                 = "mrp-rstk-qa"
    qarsf_sb_erp_mrp_ONEOFF_DYNO_TYPE         = "performance-l"
    qarsf_sb_erp_mrp_planmrp_APP_NAME         = "mrp-rstk-qa"
    qarsf_sb_erp_mrp_planmrp_ONEOFF_DYNO_TYPE = "performance-l"
  }

  # Sensitive config vars - values come from the `secrets` map supplied via
  # terraform.tfvars (gitignored). Explicit lookups so a missing key fails
  # loudly at plan time instead of silently dropping a config var.
  sensitive_config_vars = {
    HEROKU_PASSWORD      = var.secrets["HEROKU_PASSWORD"]
    HEROKU_USERNAME      = var.secrets["HEROKU_USERNAME"]
    ORMONGO_DBNAME       = var.secrets["ORMONGO_DBNAME"]
    ORMONGO_PASSWORD     = var.secrets["ORMONGO_PASSWORD"]
    ORMONGO_USERNAME     = var.secrets["ORMONGO_USERNAME"]
    RSTK_KEY             = var.secrets["RSTK_KEY"]
    SFORCE_CLIENT_KEY    = var.secrets["SFORCE_CLIENT_KEY"]
    SFORCE_CLIENT_SECRET = var.secrets["SFORCE_CLIENT_SECRET"]
  }
}

# -----------------------------------------------------------------------------
# Addon-injected config vars (NOT managed here)
# -----------------------------------------------------------------------------
# These are set automatically by the attached add-ons, so they are intentionally
# absent from the config above:
#   - CLOUDAMQP_APIKEY  -> cloudamqp (billed to web-rstk-qa)
#   - CLOUDAMQP_URL     -> cloudamqp (billed to web-rstk-qa)
#   - ORMONGO_REGION    -> ormongo (billed to worker-rstk-dev)
#   - ORMONGO_RS_URL    -> ormongo (billed to worker-rstk-dev)
#   - ORMONGO_URL       -> ormongo (billed to worker-rstk-dev)

# -----------------------------------------------------------------------------
# Shared add-ons attached to this app (billed to OTHER apps - not managed here)
# -----------------------------------------------------------------------------
#   - cloudamqp:lemur  (billed to web-rstk-qa)
#   - ormongo:2-mmap  (billed to worker-rstk-dev)
