# =============================================================================
# prerelease-worker - Heroku Application
# =============================================================================
# Part of the "pre-release" pipeline, "production" stage.
# Mirrors the live Heroku app. Shared logic and common defaults live in the
# rstk-app module; only this app's specifics are set below.
#
# Generated by tools/codify_app.py - safe to edit by hand afterwards.
# =============================================================================

module "app" {
  source = "../../../../modules/rstk-app"

  app_name       = "prerelease-worker"
  pipeline_name  = "pre-release"
  pipeline_stage = "production"

  # No GitHub integration is configured on this app (github_repo stays null,
  # which skips the Kolkrabbi wiring in the module).

  # Add-ons owned by this app
  addons = {
    papertrail = "papertrail:choklad"
  }

  # Dyno formation (live values)
  formations = {
    worker = { size = "standard-2x", quantity = 1 }
  }

  # Non-sensitive config vars. DEFAULT_MONGODB=ORMONGO comes from the module base.
  config_vars = {
    ARAGING_APP_NAME                          = "prerelease-finreport"
    ARAGING_ONEOFF_DYNO_TYPE                  = "performance-l"
    ARAGING_PROCESS_NAME                      = "newoneoff"
    DEVTESTING                                = "true"
    LOG_LEVEL                                 = "DEBUG"
    MRP_APP_NAME                              = "prerelease-new-mrp"
    MRP_ONEOFF_DYNO_TYPE                      = "performance-l"
    MRP_PROCESS_NAME                          = "myworker"
    ORMONGO_REGION                            = "IAD"
    ORMONGO_RS_URL                            = "mongodb://iad2-c0-0.mongo.objectrocket.com:53549,iad2-c0-1.mongo.objectrocket.com:53549,iad2-c0-2.mongo.objectrocket.com:53549/?replicaSet=c318ec754ba847cbbbb28313340dcd08"
    ORMONGO_URL                               = "mongodb://iad2-c0-0.mongo.objectrocket.com:53549"
    QUEUE_NAME                                = "PRERELEASE"
    RF_APP_NAME                               = "prerelease-rootf"
    RF_ONEOFF_DYNO_TYPE                       = "standard-2x"
    RF_PROCFILE_PROCESS_NAME                  = "rfworker"
    SFORCE_NAMESPACE                          = "DOX__"
    SPIN_PERFORMANCE_L_BEYOND                 = "1"
    STDCOSTS_APP_NAME                         = "prerelease-stdcosts"
    STDCOSTS_COSTROLLUP_ONEOFF_DYNO_TYPE      = "performance-l"
    STDCOSTS_CSSIMSTDMOVE_ONEOFF_DYNO_TYPE    = "performance-l"
    STDCOSTS_ICSETMTLSIMCOST_ONEOFF_DYNO_TYPE = "standard-2x"
    STDCOSTS_ONEOFF_DYNO_TYPE                 = "performance-l"
    STDCOSTS_POSETMTLCOST_ONEOFF_DYNO_TYPE    = "standard-2x"
    STDCOSTS_PROCESS_NAME                     = "oneoff"
    localeLanguage                            = "de,sv"
    supportedLocale                           = "de_AT,sv_SE,de_EN,fr_FR,da_DK,en_DE,nl_NL,de_DE,en_US,pl_PL"
  }

  # Sensitive config vars - values come from the `secrets` map supplied via
  # terraform.tfvars (gitignored). Explicit lookups so a missing key fails
  # loudly at plan time instead of silently dropping a config var.
  sensitive_config_vars = {
    API_USN              = var.secrets["API_USN"]
    API_USNKY            = var.secrets["API_USNKY"]
    CLOUDAMQP_APIKEY     = var.secrets["CLOUDAMQP_APIKEY"]
    CLOUDAMQP_URL        = var.secrets["CLOUDAMQP_URL"]
    ORMONGO_DBNAME       = var.secrets["ORMONGO_DBNAME"]
    ORMONGO_PASSWORD     = var.secrets["ORMONGO_PASSWORD"]
    ORMONGO_USERNAME     = var.secrets["ORMONGO_USERNAME"]
    RSTK_KEY             = var.secrets["RSTK_KEY"]
    SFORCE_CLIENT_KEY    = var.secrets["SFORCE_CLIENT_KEY"]
    SFORCE_CLIENT_SECRET = var.secrets["SFORCE_CLIENT_SECRET"]
  }
}

# -----------------------------------------------------------------------------
# Addon-injected config vars (NOT managed here)
# -----------------------------------------------------------------------------
# These are set automatically by the attached add-ons, so they are intentionally
# absent from the config above:
#   - PAPERTRAIL_API_TOKEN  -> papertrail (owned by this app)
