# =============================================================================
# finreport-test-last-1 - Heroku Application
# =============================================================================
# Part of the "financials" pipeline, "staging" stage.
# Mirrors the live Heroku app. Shared logic and common defaults live in the
# rstk-app module; only this app's specifics are set below.
#
# Generated by tools/codify_app.py - safe to edit by hand afterwards.
# =============================================================================

module "app" {
  source = "../../../../modules/rstk-app"

  app_name       = "finreport-test-last-1"
  pipeline_name  = "financials"
  pipeline_stage = "staging"
  stack          = "heroku-20" # differs from the module default

  # GitHub integration (live values)
  github_repo   = "rootstockmfg/hkarag"
  deploy_branch = "master"
  auto_deploy   = false
  wait_for_ci   = false

  # Add-ons owned by this app
  addons = {
    papertrail = "papertrail:choklad"
  }

  # Dyno formation (live values)
  formations = {
    newoneoff = { size = "standard-1x", quantity = 0 }
  }

  # Non-sensitive config vars. DEFAULT_MONGODB=ORMONGO comes from the module base.
  config_vars = {
    JAVA_OPTS        = "-XX:+UseG1GC -Xmx8g -Xms1g"
    PGCLIENTENCODING = "UTF8"
  }

  # Sensitive config vars - values come from the `secrets` map supplied via
  # terraform.tfvars (gitignored). Explicit lookups so a missing key fails
  # loudly at plan time instead of silently dropping a config var.
  sensitive_config_vars = {
    ORMONGO_DBNAME   = var.secrets["ORMONGO_DBNAME"]
    ORMONGO_PASSWORD = var.secrets["ORMONGO_PASSWORD"]
    ORMONGO_USERNAME = var.secrets["ORMONGO_USERNAME"]
  }
}

# -----------------------------------------------------------------------------
# Addon-injected config vars (NOT managed here)
# -----------------------------------------------------------------------------
# These are set automatically by the attached add-ons, so they are intentionally
# absent from the config above:
#   - DATABASE_URL          -> heroku-postgresql (billed to mrp-rstk-prod)
#   - ORMONGO_REGION        -> ormongo (billed to worker-rstk-test)
#   - ORMONGO_RS_URL        -> ormongo (billed to worker-rstk-test)
#   - ORMONGO_URL           -> ormongo (billed to worker-rstk-test)
#   - PAPERTRAIL_API_TOKEN  -> papertrail (owned by this app)

# -----------------------------------------------------------------------------
# Shared add-ons attached to this app (billed to OTHER apps - not managed here)
# -----------------------------------------------------------------------------
#   - heroku-postgresql:standard-2  (billed to mrp-rstk-prod)
#   - ormongo:2-mmap  (billed to worker-rstk-test)
