# =============================================================================
# prerelease-rootf - Heroku Application
# =============================================================================
# Part of the "pre-release" pipeline, "production" stage.
# Mirrors the live Heroku app. Shared logic and common defaults live in the
# rstk-app module; only this app's specifics are set below.
#
# Generated by tools/codify_app.py - safe to edit by hand afterwards.
# =============================================================================

module "app" {
  source = "../../../../modules/rstk-app"

  app_name       = "prerelease-rootf"
  pipeline_name  = "pre-release"
  pipeline_stage = "production"
  stack          = "heroku-22" # differs from the module default

  # No GitHub integration is configured on this app (github_repo stays null,
  # which skips the Kolkrabbi wiring in the module).

  # Add-ons owned by this app
  addons = {
    papertrail = "papertrail:choklad"
  }

  # Dyno formation (live values)
  formations = {
    rfworker = { size = "standard-1x", quantity = 0 }
  }

  # Non-sensitive config vars. DEFAULT_MONGODB=ORMONGO comes from the module base.
  config_vars = {
    ORMONGO_REGION      = "IAD"
    ORMONGO_RS_URL      = "mongodb://iad2-c0-0.mongo.objectrocket.com:53549,iad2-c0-1.mongo.objectrocket.com:53549,iad2-c0-2.mongo.objectrocket.com:53549/?replicaSet=c318ec754ba847cbbbb28313340dcd08"
    ORMONGO_URL         = "mongodb://iad2-c0-0.mongo.objectrocket.com:53549"
    SFORCE_NAMESPACE    = "DOX__"
    SFORCE_REDIRECT_URL = "https://web-RSTK-PROD.herokuapp.com/sf/oauth/callback"
    supportedLocale     = "de_AT,sv_SE,en_GB, nl_NL"
  }

  # Sensitive config vars - values come from the `secrets` map supplied via
  # terraform.tfvars (gitignored). Explicit lookups so a missing key fails
  # loudly at plan time instead of silently dropping a config var.
  sensitive_config_vars = {
    ORMONGO_DBNAME       = var.secrets["ORMONGO_DBNAME"]
    ORMONGO_PASSWORD     = var.secrets["ORMONGO_PASSWORD"]
    ORMONGO_USERNAME     = var.secrets["ORMONGO_USERNAME"]
    SFORCE_CLIENT_KEY    = var.secrets["SFORCE_CLIENT_KEY"]
    SFORCE_CLIENT_SECRET = var.secrets["SFORCE_CLIENT_SECRET"]
  }
}

# -----------------------------------------------------------------------------
# Addon-injected config vars (NOT managed here)
# -----------------------------------------------------------------------------
# These are set automatically by the attached add-ons, so they are intentionally
# absent from the config above:
#   - PAPERTRAIL_API_TOKEN  -> papertrail (owned by this app)
