# =============================================================================
# worker-with-rootf-jar - Heroku Application
# =============================================================================
# Part of the "worker" pipeline, "development" stage.
# Mirrors the live Heroku app. Shared logic and common defaults live in the
# rstk-app module; only this app's specifics are set below.
#
# Generated by tools/codify_app.py - safe to edit by hand afterwards.
# =============================================================================

module "app" {
  source = "../../../../modules/rstk-app"

  app_name      = "worker-with-rootf-jar"
  pipeline_name = "worker"
  # pipeline_stage defaults to "development"
  stack = "heroku-22" # differs from the module default

  # No GitHub integration is configured on this app (github_repo stays null,
  # which skips the Kolkrabbi wiring in the module).

  # Add-ons owned by this app
  addons = {
    papertrail = "papertrail:choklad"
  }

  # Dyno formation (live values)
  formations = {
    worker = { size = "standard-2x", quantity = 0 }
  }

  # Non-sensitive config vars. DEFAULT_MONGODB=ORMONGO comes from the module base.
  config_vars = {
    LOG_LEVEL                                                 = "DEBUG"
    QUEUE_NAME                                                = "CURR"
    RF_APP_NAME                                               = "rootf-dev"
    RF_ONEOFF_DYNO_TYPE                                       = "standard-2x"
    RF_PROCFILE_PROCESS_NAME                                  = "rfworker"
    SFORCE_NAMESPACE                                          = "DOX__"
    pde3_erp_mrp_planmrp_APP_NAME                             = "mrp-rstk-dev"
    pde3_erp_mrp_planmrp_PROCFILE_PROCESS_NAME                = "myworker"
    pde3_erp_stdcosts_costrollup_APP_NAME                     = "stdcosts-dev"
    pde3_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME        = "oneoff"
    pde3f_finance_araging_APP_NAME                            = "finreport-rstk-dev"
    pde3f_finance_araging_ONEOFF_DYNO_TYPE                    = "performance-l"
    pde3f_finance_araging_PROCFILE_PROCESS_NAME               = "newoneoff"
    pde3f_finance_araging_aragingreport_APP_NAME              = "finreport-rstk-dev"
    pde3f_finance_araging_aragingreport_ONEOFF_DYNO_TYPE      = "performance-l"
    pde3f_finance_araging_aragingreport_PROCFILE_PROCESS_NAME = "newoneoff"
    pde5_erp_stdcosts_costrollup_APP_NAME                     = "stdcosts-dev"
    pde5_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME        = "oneoff"
  }

  # Sensitive config vars - values come from the `secrets` map supplied via
  # terraform.tfvars (gitignored). Explicit lookups so a missing key fails
  # loudly at plan time instead of silently dropping a config var.
  sensitive_config_vars = {
    API_USN              = var.secrets["API_USN"]
    API_USNKY            = var.secrets["API_USNKY"]
    HEROKU_PASSWORD      = var.secrets["HEROKU_PASSWORD"]
    HEROKU_USERNAME      = var.secrets["HEROKU_USERNAME"]
    ORMONGO_DBNAME       = var.secrets["ORMONGO_DBNAME"]
    ORMONGO_PASSWORD     = var.secrets["ORMONGO_PASSWORD"]
    ORMONGO_USERNAME     = var.secrets["ORMONGO_USERNAME"]
    RSTK_KEY             = var.secrets["RSTK_KEY"]
    SFORCE_CLIENT_KEY    = var.secrets["SFORCE_CLIENT_KEY"]
    SFORCE_CLIENT_SECRET = var.secrets["SFORCE_CLIENT_SECRET"]
  }
}

# -----------------------------------------------------------------------------
# Addon-injected config vars (NOT managed here)
# -----------------------------------------------------------------------------
# These are set automatically by the attached add-ons, so they are intentionally
# absent from the config above:
#   - CLOUDAMQP_APIKEY      -> cloudamqp (billed to web-rstk-dev)
#   - CLOUDAMQP_URL         -> cloudamqp (billed to web-rstk-dev)
#   - DATABASE_URL          -> heroku-postgresql (billed to mrp-rstk-prod)
#   - ORMONGO_REGION        -> ormongo (billed to worker-rstk-dev)
#   - ORMONGO_RS_URL        -> ormongo (billed to worker-rstk-dev)
#   - ORMONGO_URL           -> ormongo (billed to worker-rstk-dev)
#   - PAPERTRAIL_API_TOKEN  -> papertrail (owned by this app)

# -----------------------------------------------------------------------------
# Shared add-ons attached to this app (billed to OTHER apps - not managed here)
# -----------------------------------------------------------------------------
#   - cloudamqp:squirrel-1  (billed to web-rstk-dev)
#   - heroku-postgresql:standard-2  (billed to mrp-rstk-prod)
#   - ormongo:2-mmap  (billed to worker-rstk-dev)
