# =============================================================================
# stdcosts-test - Heroku Application
# =============================================================================
# Part of the "stdcosts" pipeline, "staging" stage.
# Mirrors the live Heroku app. Shared logic and common defaults live in the
# rstk-app module; only this app's specifics are set below.
#
# Generated by tools/codify_app.py - safe to edit by hand afterwards.
# =============================================================================

module "app" {
  source = "../../../../modules/rstk-app"

  app_name       = "stdcosts-test"
  pipeline_name  = "stdcosts"
  pipeline_stage = "staging"

  # No GitHub integration is configured on this app (github_repo stays null,
  # which skips the Kolkrabbi wiring in the module).

  # Add-ons owned by this app
  addons = {
    papertrail = "papertrail:ludvig"
  }

  # Dyno formation (live values)
  formations = {
    oneoff = { size = "standard-1x", quantity = 0 }
  }

  # Non-sensitive config vars. DEFAULT_MONGODB=ORMONGO comes from the module base.
  config_vars = {
    JAVA_OPTS        = "-XX:+UseG1GC -Xmx8g -Xms2g"
    LOG_LEVEL        = "FINEST"
    PGCLIENTENCODING = "UTF8"
  }

  # Sensitive config vars - values come from the `secrets` map supplied via
  # terraform.tfvars (gitignored). Explicit lookups so a missing key fails
  # loudly at plan time instead of silently dropping a config var.
  sensitive_config_vars = {
    CLOUDAMQP_APIKEY = var.secrets["CLOUDAMQP_APIKEY"]
    CLOUDAMQP_URL    = var.secrets["CLOUDAMQP_URL"]
    ORMONGO_DBNAME   = var.secrets["ORMONGO_DBNAME"]
    ORMONGO_PASSWORD = var.secrets["ORMONGO_PASSWORD"]
    ORMONGO_USERNAME = var.secrets["ORMONGO_USERNAME"]
  }
}

# -----------------------------------------------------------------------------
# Addon-injected config vars (NOT managed here)
# -----------------------------------------------------------------------------
# These are set automatically by the attached add-ons, so they are intentionally
# absent from the config above:
#   - DATABASE_URL          -> heroku-postgresql (billed to mrp-rstk-prod)
#   - ORMONGO_REGION        -> ormongo (billed to worker-rstk-test)
#   - ORMONGO_RS_URL        -> ormongo (billed to worker-rstk-test)
#   - ORMONGO_URL           -> ormongo (billed to worker-rstk-test)
#   - PAPERTRAIL_API_TOKEN  -> papertrail (owned by this app)

# -----------------------------------------------------------------------------
# Shared add-ons attached to this app (billed to OTHER apps - not managed here)
# -----------------------------------------------------------------------------
#   - heroku-postgresql:standard-2  (billed to mrp-rstk-prod)
#   - ormongo:2-mmap  (billed to worker-rstk-test)
