# =============================================================================
# web-rstk-qa - Heroku Application
# =============================================================================
# Part of the "web" pipeline, "staging" stage.
# Mirrors the live Heroku app. Shared logic and common defaults live in the
# rstk-app module; only this app's specifics are set below.
#
# Generated by tools/codify_app.py - safe to edit by hand afterwards.
# =============================================================================

module "app" {
  source = "../../../../modules/rstk-app"

  app_name       = "web-rstk-qa"
  pipeline_name  = "web"
  pipeline_stage = "staging"
  stack          = "heroku-22" # differs from the module default

  # No GitHub integration is configured on this app (github_repo stays null,
  # which skips the Kolkrabbi wiring in the module).

  # Add-ons owned by this app
  addons = {
    cloudamqp  = "cloudamqp:lemur"
    papertrail = "papertrail:choklad"
  }

  # Dyno formation (live values)
  formations = {
    web = { size = "standard-1x", quantity = 1 }
  }

  # Non-sensitive config vars. DEFAULT_MONGODB=ORMONGO comes from the module base.
  config_vars = {
    APPS_REDIRECT_URL            = "https://web-rstk-qa.herokuapp.com/sf/oauth/callback"
    CAPTURE_POLL_INTERVAL_MINS   = "60"
    CAPTURE_REQUEST_RATE         = "true"
    CATG_SMALL_ORGS              = "00D1a000000ZQ8oEAG"
    ENABLE_STORE_REQUEST_FEATURE = "TRUE"
    LOG_LEVEL                    = "DEBUG"
    QNAME_B4TICKET_ROOTF         = "LAST-0"
    REQ_THRESHOLD_SMALL          = "10"
    "ROOTF_VERSIONS_LAST-0"      = ""
    ROUTED_ORGS_2                = ""
    ROUTED_ORGS_3                = ""
    ROUTED_ORGS_5                = ""
    ROUTED_QNAME_1               = "ROUTED_1"
    ROUTED_QNAME_2               = "ROUTED_2"
    ROUTED_QNAME_3               = "ROUTED_3"
    ROUTED_QNAME_5               = "ROUTED_5"
    SFORCE_REDIRECT_URL          = "https://web-rstk-qa.herokuapp.com/sf/oauth/callback"
    SRC_ORG_QNAME                = "CURR"
    "STDCOSTS_VERSIONS_LAST-0"   = ""
    TEST_ORGS                    = ""
    TEST_QNAME                   = ""
    USE_OLDER_IMPL               = "FALSE"
  }

  # Sensitive config vars - values come from the `secrets` map supplied via
  # terraform.tfvars (gitignored). Explicit lookups so a missing key fails
  # loudly at plan time instead of silently dropping a config var.
  sensitive_config_vars = {
    APPS_CLIENT_KEY      = var.secrets["APPS_CLIENT_KEY"]
    APPS_CLIENT_SECRET   = var.secrets["APPS_CLIENT_SECRET"]
    ORMONGO_DBNAME       = var.secrets["ORMONGO_DBNAME"]
    ORMONGO_PASSWORD     = var.secrets["ORMONGO_PASSWORD"]
    ORMONGO_USERNAME     = var.secrets["ORMONGO_USERNAME"]
    RSTK_KEY             = var.secrets["RSTK_KEY"]
    SFORCE_CLIENT_KEY    = var.secrets["SFORCE_CLIENT_KEY"]
    SFORCE_CLIENT_SECRET = var.secrets["SFORCE_CLIENT_SECRET"]
    pde5_dbname          = var.secrets["pde5_dbname"]
  }
}

# -----------------------------------------------------------------------------
# Addon-injected config vars (NOT managed here)
# -----------------------------------------------------------------------------
# These are set automatically by the attached add-ons, so they are intentionally
# absent from the config above:
#   - CLOUDAMQP_APIKEY      -> cloudamqp (owned by this app)
#   - CLOUDAMQP_URL         -> cloudamqp (owned by this app)
#   - DATABASE_URL          -> heroku-postgresql (billed to mrp-rstk-prod)
#   - ORMONGO_REGION        -> ormongo (billed to worker-rstk-dev)
#   - ORMONGO_RS_URL        -> ormongo (billed to worker-rstk-dev)
#   - ORMONGO_URL           -> ormongo (billed to worker-rstk-dev)
#   - PAPERTRAIL_API_TOKEN  -> papertrail (owned by this app)

# -----------------------------------------------------------------------------
# Shared add-ons attached to this app (billed to OTHER apps - not managed here)
# -----------------------------------------------------------------------------
#   - heroku-postgresql:standard-2  (billed to mrp-rstk-prod)
#   - ormongo:2-mmap  (billed to worker-rstk-dev)
