# =============================================================================
# worker-test-last-0 - Heroku Application
# =============================================================================
# Part of the "worker" pipeline, "staging" stage.
# Mirrors the live Heroku app. Shared logic and common defaults live in the
# rstk-app module; only this app's specifics are set below.
#
# Generated by tools/codify_app.py - safe to edit by hand afterwards.
# =============================================================================

module "app" {
  source = "../../../../modules/rstk-app"

  app_name       = "worker-test-last-0"
  pipeline_name  = "worker"
  pipeline_stage = "staging"

  # No GitHub integration is configured on this app (github_repo stays null,
  # which skips the Kolkrabbi wiring in the module).

  # Add-ons owned by this app
  addons = {
    papertrail = "papertrail:choklad"
  }

  # Dyno formation (live values)
  formations = {
    worker = { size = "standard-2x", quantity = 1 }
  }

  # Non-sensitive config vars. DEFAULT_MONGODB=ORMONGO comes from the module base.
  config_vars = {
    ARAGING_APP_NAME                                                             = "finreport-test-last-0"
    ARAGING_ONEOFF_DYNO_TYPE                                                     = "performance-l"
    ARAGING_PROCESS_NAME                                                         = "newoneoff"
    BOTH_MONGOS                                                                  = "TRUE"
    LOG_LEVEL                                                                    = "DEBUG"
    MRP_APP_NAME                                                                 = "mrp-rstk-test"
    MRP_ONEOFF_DYNO_TYPE                                                         = "performance-l"
    MRP_PROCESS_NAME                                                             = "myworker"
    QUEUE_NAME                                                                   = "LAST-0"
    RF_APP_NAME                                                                  = "rootf-test-last-0"
    RF_ONEOFF_DYNO_TYPE                                                          = "standard-2x"
    RF_PROCFILE_PROCESS_NAME                                                     = "rfworker"
    SFORCE_NAMESPACE                                                             = "DOX__"
    STDCOSTS_APP_NAME                                                            = "stdcosts-test-last-0"
    STDCOSTS_COSTROLLUP_ONEOFF_DYNO_TYPE                                         = "performance-l"
    STDCOSTS_CSSIMSTDMOVE_ONEOFF_DYNO_TYPE                                       = "performance-l"
    STDCOSTS_ICSETMTLSIMCOST_ONEOFF_DYNO_TYPE                                    = "standard-2x"
    STDCOSTS_ONEOFF_DYNO_TYPE                                                    = "performance-l"
    STDCOSTS_POSETMTLCOST_ONEOFF_DYNO_TYPE                                       = "standard-2x"
    STDCOSTS_PROCESS_NAME                                                        = "oneoff"
    aphria_b2b_finance_araging_APP_NAME                                          = "finreport-test-last-2"
    aphria_b2b_finance_araging_ONEOFF_DYNO_TYPE                                  = "performance-l"
    aphria_b2b_finance_araging_PROCFILE_PROCESS_NAME                             = "newoneoff"
    aphria_b2b_finance_araging_aragingreport_APP_NAME                            = "finreport-test-last-2"
    aphria_b2b_finance_araging_aragingreport_ONEOFF_DYNO_TYPE                    = "performance-l"
    aphria_b2b_finance_araging_aragingreport_PROCFILE_PROCESS_NAME               = "newoneoff"
    aphria_sit_erp_stdcosts_costrollup_APP_NAME                                  = "stdcosts-test-last-0"
    aphria_sit_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE                          = "performance-l"
    aphria_sit_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME                     = "oneoff"
    aphria_sit_erp_stdcosts_cssimstdmove_APP_NAME                                = "stdcosts-test-last-0"
    aphria_sit_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE                        = "performance-l"
    aphria_sit_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME                   = "oneoff"
    aphria_sit_erp_stdcosts_icsetmtlsimcost_APP_NAME                             = "stdcosts-test-last-0"
    aphria_sit_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE                     = "performance-l"
    aphria_sit_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME                = "oneoff"
    aphria_sit_erp_stdcosts_posetmtlcost_APP_NAME                                = "stdcosts-test-last-0"
    aphria_sit_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE                        = "performance-l"
    aphria_sit_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME                   = "oneoff"
    aphria_sit_finance_araging_APP_NAME                                          = "finreport-test-last-0"
    aphria_sit_finance_araging_ONEOFF_DYNO_TYPE                                  = "performance-l"
    aphria_sit_finance_araging_PROCFILE_PROCESS_NAME                             = "newoneoff"
    aphria_sit_finance_araging_aragingreport_APP_NAME                            = "finreport-test-last-0"
    aphria_sit_finance_araging_aragingreport_ONEOFF_DYNO_TYPE                    = "performance-l"
    aphria_sit_finance_araging_aragingreport_PROCFILE_PROCESS_NAME               = "newoneoff"
    aphria_uat_erp_stdcosts_costrollup_APP_NAME                                  = "stdcosts-test-last-0"
    aphria_uat_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE                          = "performance-l"
    aphria_uat_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME                     = "oneoff"
    aphria_uat_erp_stdcosts_cssimstdmove_APP_NAME                                = "stdcosts-test-last-0"
    aphria_uat_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE                        = "performance-l"
    aphria_uat_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME                   = "oneoff"
    aphria_uat_erp_stdcosts_icsetmtlsimcost_APP_NAME                             = "stdcosts-test-last-0"
    aphria_uat_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE                     = "performance-l"
    aphria_uat_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME                = "oneoff"
    aphria_uat_erp_stdcosts_posetmtlcost_APP_NAME                                = "stdcosts-test-last-0"
    aphria_uat_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE                        = "performance-l"
    aphria_uat_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME                   = "oneoff"
    aphria_uat_finance_araging_APP_NAME                                          = "finreport-test-last-0"
    aphria_uat_finance_araging_ONEOFF_DYNO_TYPE                                  = "performance-l"
    aphria_uat_finance_araging_PROCFILE_PROCESS_NAME                             = "newoneoff"
    aphria_uat_finance_araging_aragingreport_APP_NAME                            = "finreport-test-last-0"
    aphria_uat_finance_araging_aragingreport_ONEOFF_DYNO_TYPE                    = "performance-l"
    aphria_uat_finance_araging_aragingreport_PROCFILE_PROCESS_NAME               = "newoneoff"
    betabionics_rspilot_erp_stdcosts_costrollup_APP_NAME                         = "stdcosts-test-last-0"
    betabionics_rspilot_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE                 = "performance-l"
    betabionics_rspilot_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME            = "oneoff"
    betabionics_rspilot_erp_stdcosts_cssimstdmove_APP_NAME                       = "stdcosts-test-last-0"
    betabionics_rspilot_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE               = "performance-l"
    betabionics_rspilot_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME          = "oneoff"
    betabionics_rspilot_erp_stdcosts_icsetmtlsimcost_APP_NAME                    = "stdcosts-test-last-0"
    betabionics_rspilot_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE            = "performance-l"
    betabionics_rspilot_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME       = "oneoff"
    betabionics_rspilot_erp_stdcosts_posetmtlcost_APP_NAME                       = "stdcosts-test-last-0"
    betabionics_rspilot_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE               = "performance-l"
    betabionics_rspilot_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME          = "oneoff"
    cottenham_rspilot_finance_araging_APP_NAME                                   = "finreport-test-last-2"
    cottenham_rspilot_finance_araging_ONEOFF_DYNO_TYPE                           = "performance-l"
    cottenham_rspilot_finance_araging_PROCFILE_PROCESS_NAME                      = "newoneoff"
    cottenham_rspilot_finance_araging_aragingreport_APP_NAME                     = "finreport-test-last-2"
    cottenham_rspilot_finance_araging_aragingreport_ONEOFF_DYNO_TYPE             = "performance-l"
    cottenham_rspilot_finance_araging_aragingreport_PROCFILE_PROCESS_NAME        = "newoneoff"
    duracompositesltd_rspilot_erp_stdcosts_costrollup_APP_NAME                   = "stdcosts-test-last-0"
    duracompositesltd_rspilot_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE           = "performance-l"
    duracompositesltd_rspilot_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME      = "oneoff"
    duracompositesltd_rspilot_erp_stdcosts_cssimstdmove_APP_NAME                 = "stdcosts-test-last-0"
    duracompositesltd_rspilot_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE         = "performance-l"
    duracompositesltd_rspilot_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME    = "oneoff"
    duracompositesltd_rspilot_erp_stdcosts_icsetmtlsimcost_APP_NAME              = "stdcosts-test-last-0"
    duracompositesltd_rspilot_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE      = "performance-l"
    duracompositesltd_rspilot_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME = "oneoff"
    duracompositesltd_rspilot_erp_stdcosts_posetmtlcost_APP_NAME                 = "stdcosts-test-last-0"
    duracompositesltd_rspilot_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE         = "performance-l"
    duracompositesltd_rspilot_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME    = "oneoff"
    fike_stage_erp_stdcosts_costrollup_APP_NAME                                  = "stdcosts-test-last-0"
    fike_stage_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE                          = "performance-l"
    fike_stage_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME                     = "oneoff"
    fike_stage_erp_stdcosts_cssimstdmove_APP_NAME                                = "stdcosts-test-last-0"
    fike_stage_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE                        = "performance-l"
    fike_stage_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME                   = "oneoff"
    fike_stage_erp_stdcosts_icsetmtlsimcost_APP_NAME                             = "stdcosts-test-last-0"
    fike_stage_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE                     = "performance-l"
    fike_stage_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME                = "oneoff"
    fike_stage_erp_stdcosts_posetmtlcost_APP_NAME                                = "stdcosts-test-last-0"
    fike_stage_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE                        = "performance-l"
    fike_stage_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME                   = "oneoff"
    geometrics_rspilot_erp_stdcosts_costrollup_APP_NAME                          = "stdcosts-test-last-0"
    geometrics_rspilot_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE                  = "performance-l"
    geometrics_rspilot_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME             = "oneoff"
    geometrics_rspilot_erp_stdcosts_cssimstdmove_APP_NAME                        = "stdcosts-test-last-0"
    geometrics_rspilot_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE                = "performance-l"
    geometrics_rspilot_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME           = "oneoff"
    geometrics_rspilot_erp_stdcosts_icsetmtlsimcost_APP_NAME                     = "stdcosts-test-last-0"
    geometrics_rspilot_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE             = "performance-l"
    geometrics_rspilot_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME        = "oneoff"
    geometrics_rspilot_erp_stdcosts_posetmtlcost_APP_NAME                        = "stdcosts-test-last-0"
    geometrics_rspilot_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE                = "performance-l"
    geometrics_rspilot_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME           = "oneoff"
    jdc_fullrec_erp_stdcosts_costrollup_APP_NAME                                 = "stdcosts-test-last-0"
    jdc_fullrec_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE                         = "performance-l"
    jdc_fullrec_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME                    = "oneoff"
    jdc_fullrec_erp_stdcosts_cssimstdmove_APP_NAME                               = "stdcosts-test-last-0"
    jdc_fullrec_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE                       = "performance-l"
    jdc_fullrec_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME                  = "oneoff"
    jdc_fullrec_erp_stdcosts_icsetmtlsimcost_APP_NAME                            = "stdcosts-test-last-0"
    jdc_fullrec_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE                    = "performance-l"
    jdc_fullrec_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME               = "oneoff"
    jdc_fullrec_erp_stdcosts_posetmtlcost_APP_NAME                               = "stdcosts-test-last-0"
    jdc_fullrec_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE                       = "performance-l"
    jdc_fullrec_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME                  = "oneoff"
    jdc_rspilot_erp_stdcosts_costrollup_APP_NAME                                 = "stdcosts-test-last-0"
    jdc_rspilot_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE                         = "performance-l"
    jdc_rspilot_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME                    = "oneoff"
    jdc_rspilot_erp_stdcosts_cssimstdmove_APP_NAME                               = "stdcosts-test-last-0"
    jdc_rspilot_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE                       = "performance-l"
    jdc_rspilot_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME                  = "oneoff"
    jdc_rspilot_erp_stdcosts_icsetmtlsimcost_APP_NAME                            = "stdcosts-test-last-0"
    jdc_rspilot_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE                    = "performance-l"
    jdc_rspilot_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME               = "oneoff"
    jdc_rspilot_erp_stdcosts_posetmtlcost_APP_NAME                               = "stdcosts-test-last-0"
    jdc_rspilot_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE                       = "performance-l"
    jdc_rspilot_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME                  = "oneoff"
    kline_rspilot_erp_stdcosts_costrollup_APP_NAME                               = "stdcosts-test-last-0"
    kline_rspilot_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE                       = "performance-l"
    kline_rspilot_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME                  = "oneoff"
    kline_rspilot_erp_stdcosts_cssimstdmove_APP_NAME                             = "stdcosts-test-last-0"
    kline_rspilot_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE                     = "performance-l"
    kline_rspilot_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME                = "oneoff"
    kline_rspilot_erp_stdcosts_icsetmtlsimcost_APP_NAME                          = "stdcosts-test-last-0"
    kline_rspilot_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE                  = "performance-l"
    kline_rspilot_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME             = "oneoff"
    kline_rspilot_erp_stdcosts_posetmtlcost_APP_NAME                             = "stdcosts-test-last-0"
    kline_rspilot_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE                     = "performance-l"
    kline_rspilot_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME                = "oneoff"
    matouk_sb_erp_stdcosts_costrollup_APP_NAME                                   = "stdcosts-test-last-0"
    matouk_sb_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE                           = "performance-l"
    matouk_sb_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME                      = "oneoff"
    matouk_sb_erp_stdcosts_cssimstdmove_APP_NAME                                 = "stdcosts-test-last-0"
    matouk_sb_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE                         = "performance-l"
    matouk_sb_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME                    = "oneoff"
    matouk_sb_erp_stdcosts_icsetmtlsimcost_APP_NAME                              = "stdcosts-test-last-0"
    matouk_sb_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE                      = "performance-l"
    matouk_sb_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME                 = "oneoff"
    matouk_sb_erp_stdcosts_posetmtlcost_APP_NAME                                 = "stdcosts-test-last-0"
    matouk_sb_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE                         = "performance-l"
    matouk_sb_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME                    = "oneoff"
    mdf_fullsand_finance_araging_APP_NAME                                        = "finreport-test-last-2"
    mdf_fullsand_finance_araging_ONEOFF_DYNO_TYPE                                = "performance-l"
    mdf_fullsand_finance_araging_PROCFILE_PROCESS_NAME                           = "newoneoff"
    mdf_fullsand_finance_araging_aragingreport_APP_NAME                          = "finreport-test-last-2"
    mdf_fullsand_finance_araging_aragingreport_ONEOFF_DYNO_TYPE                  = "performance-l"
    mdf_fullsand_finance_araging_aragingreport_PROCFILE_PROCESS_NAME             = "newoneoff"
    mevion_sb_erp_stdcosts_costrollup_APP_NAME                                   = "stdcosts-test-last-0"
    mevion_sb_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE                           = "performance-l"
    mevion_sb_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME                      = "oneoff"
    mevion_sb_erp_stdcosts_cssimstdmove_APP_NAME                                 = "stdcosts-test-last-0"
    mevion_sb_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE                         = "performance-l"
    mevion_sb_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME                    = "oneoff"
    mevion_sb_erp_stdcosts_icsetmtlsimcost_APP_NAME                              = "stdcosts-test-last-0"
    mevion_sb_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE                      = "performance-l"
    mevion_sb_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME                 = "oneoff"
    mevion_sb_erp_stdcosts_posetmtlcost_APP_NAME                                 = "stdcosts-test-last-0"
    mevion_sb_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE                         = "performance-l"
    mevion_sb_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME                    = "oneoff"
    pacer_sbox_erp_stdcosts_costrollup_APP_NAME                                  = "stdcosts-test-last-0"
    pacer_sbox_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE                          = "performance-l"
    pacer_sbox_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME                     = "oneoff"
    pacer_sbox_erp_stdcosts_cssimstdmove_APP_NAME                                = "stdcosts-test-last-0"
    pacer_sbox_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE                        = "performance-l"
    pacer_sbox_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME                   = "oneoff"
    pacer_sbox_erp_stdcosts_icsetmtlsimcost_APP_NAME                             = "stdcosts-test-last-0"
    pacer_sbox_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE                     = "performance-l"
    pacer_sbox_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME                = "oneoff"
    pacer_sbox_erp_stdcosts_posetmtlcost_APP_NAME                                = "stdcosts-test-last-0"
    pacer_sbox_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE                        = "performance-l"
    pacer_sbox_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME                   = "oneoff"
    qarsf_sb_erp_mrp_APP_NAME                                                    = "mrp-rstk-test"
    qarsf_sb_erp_mrp_ONEOFF_DYNO_TYPE                                            = "performance-l"
    qarsf_sb_erp_mrp_planmrp_APP_NAME                                            = "mrp-rstk-test"
    qarsf_sb_erp_mrp_planmrp_ONEOFF_DYNO_TYPE                                    = "performance-l"
    qarsf_sb_erp_stdcosts_costrollup_APP_NAME                                    = "stdcosts-test-last-0"
    qarsf_sb_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE                            = "performance-l"
    qarsf_sb_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME                       = "oneoff"
    qarsf_sb_erp_stdcosts_cssimstdmove_APP_NAME                                  = "stdcosts-test-last-0"
    qarsf_sb_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE                          = "performance-l"
    qarsf_sb_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME                     = "oneoff"
    qarsf_sb_erp_stdcosts_icsetmtlsimcost_APP_NAME                               = "stdcosts-test-last-0"
    qarsf_sb_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE                       = "performance-l"
    qarsf_sb_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME                  = "oneoff"
    qarsf_sb_erp_stdcosts_posetmtlcost_APP_NAME                                  = "stdcosts-test-last-0"
    qarsf_sb_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE                          = "performance-l"
    qarsf_sb_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME                     = "oneoff"
    qarsf_sb_finance_araging_APP_NAME                                            = "finreport-test-last-2"
    qarsf_sb_finance_araging_ONEOFF_DYNO_TYPE                                    = "performance-l"
    qarsf_sb_finance_araging_PROCFILE_PROCESS_NAME                               = "newoneoff"
    qarsf_sb_finance_araging_aragingreport_APP_NAME                              = "finreport-test-last-2"
    qarsf_sb_finance_araging_aragingreport_ONEOFF_DYNO_TYPE                      = "performance-l"
    qarsf_sb_finance_araging_aragingreport_PROCFILE_PROCESS_NAME                 = "newoneoff"
    unionwear_rspilot_erp_stdcosts_costrollup_APP_NAME                           = "stdcosts-test-last-0"
    unionwear_rspilot_erp_stdcosts_costrollup_ONEOFF_DYNO_TYPE                   = "performance-l"
    unionwear_rspilot_erp_stdcosts_costrollup_PROCFILE_PROCESS_NAME              = "oneoff"
    unionwear_rspilot_erp_stdcosts_cssimstdmove_APP_NAME                         = "stdcosts-test-last-0"
    unionwear_rspilot_erp_stdcosts_cssimstdmove_ONEOFF_DYNO_TYPE                 = "performance-l"
    unionwear_rspilot_erp_stdcosts_cssimstdmove_PROCFILE_PROCESS_NAME            = "oneoff"
    unionwear_rspilot_erp_stdcosts_icsetmtlsimcost_APP_NAME                      = "stdcosts-test-last-0"
    unionwear_rspilot_erp_stdcosts_icsetmtlsimcost_ONEOFF_DYNO_TYPE              = "performance-l"
    unionwear_rspilot_erp_stdcosts_icsetmtlsimcost_PROCFILE_PROCESS_NAME         = "oneoff"
    unionwear_rspilot_erp_stdcosts_posetmtlcost_APP_NAME                         = "stdcosts-test-last-0"
    unionwear_rspilot_erp_stdcosts_posetmtlcost_ONEOFF_DYNO_TYPE                 = "performance-l"
    unionwear_rspilot_erp_stdcosts_posetmtlcost_PROCFILE_PROCESS_NAME            = "oneoff"
    whiting_sb_erp_mrp_APP_NAME                                                  = "mrp-rstk-test"
    whiting_sb_erp_mrp_ONEOFF_DYNO_TYPE                                          = "performance-l"
    whiting_sb_erp_mrp_PROCFILE_PROCESS_NAME                                     = "myworker"
    whiting_sb_erp_mrp_planmrp_APP_NAME                                          = "mrp-rstk-test"
    whiting_sb_erp_mrp_planmrp_ONEOFF_DYNO_TYPE                                  = "performance-l"
    whiting_sb_erp_mrp_planmrp__PROCFILE_PROCESS_NAME                            = "myworker"
    whiting_sb_finance_araging_APP_NAME                                          = "finreport-test-last-2"
    whiting_sb_finance_araging_ONEOFF_DYNO_TYPE                                  = "performance-l"
    whiting_sb_finance_araging_PROCFILE_PROCESS_NAME                             = "newoneoff"
    whiting_sb_finance_araging_aragingreport_APP_NAME                            = "finreport-test-last-2"
    whiting_sb_finance_araging_aragingreport_ONEOFF_DYNO_TYPE                    = "performance-l"
    whiting_sb_finance_araging_aragingreport_PROCFILE_PROCESS_NAME               = "newoneoff"
  }

  # Sensitive config vars - values come from the `secrets` map supplied via
  # terraform.tfvars (gitignored). Explicit lookups so a missing key fails
  # loudly at plan time instead of silently dropping a config var.
  sensitive_config_vars = {
    API_USN              = var.secrets["API_USN"]
    API_USNKY            = var.secrets["API_USNKY"]
    CLOUDAMQP_APIKEY     = var.secrets["CLOUDAMQP_APIKEY"]
    CLOUDAMQP_URL        = var.secrets["CLOUDAMQP_URL"]
    HEROKU_PASSWORD      = var.secrets["HEROKU_PASSWORD"]
    HEROKU_USERNAME      = var.secrets["HEROKU_USERNAME"]
    ORMONGO_DBNAME       = var.secrets["ORMONGO_DBNAME"]
    ORMONGO_PASSWORD     = var.secrets["ORMONGO_PASSWORD"]
    ORMONGO_USERNAME     = var.secrets["ORMONGO_USERNAME"]
    RSTK_KEY             = var.secrets["RSTK_KEY"]
    SFORCE_CLIENT_KEY    = var.secrets["SFORCE_CLIENT_KEY"]
    SFORCE_CLIENT_SECRET = var.secrets["SFORCE_CLIENT_SECRET"]
  }
}

# -----------------------------------------------------------------------------
# Addon-injected config vars (NOT managed here)
# -----------------------------------------------------------------------------
# These are set automatically by the attached add-ons, so they are intentionally
# absent from the config above:
#   - ORMONGO_REGION        -> ormongo (billed to worker-rstk-test)
#   - ORMONGO_RS_URL        -> ormongo (billed to worker-rstk-test)
#   - ORMONGO_URL           -> ormongo (billed to worker-rstk-test)
#   - PAPERTRAIL_API_TOKEN  -> papertrail (owned by this app)

# -----------------------------------------------------------------------------
# Shared add-ons attached to this app (billed to OTHER apps - not managed here)
# -----------------------------------------------------------------------------
#   - ormongo:2-mmap  (billed to worker-rstk-test)
