# =============================================================================
# finreport-qa-last-0 - Heroku Application
# =============================================================================
# Part of the "financials" pipeline, "staging" stage.
# Mirrors the live Heroku app. Shared logic and common defaults live in the
# rstk-app module; only this app's specifics are set below.
#
# Generated by tools/codify_app.py - safe to edit by hand afterwards.
# =============================================================================

module "app" {
  source = "../../../../modules/rstk-app"

  app_name       = "finreport-qa-last-0"
  pipeline_name  = "financials"
  pipeline_stage = "staging"

  # GitHub integration (live values)
  github_repo   = "rootstockmfg/hkarag"
  deploy_branch = "master"
  auto_deploy   = false
  wait_for_ci   = false

  # This app owns no add-ons
  addons = {}

  # Dyno formation (live values)
  formations = {
    newoneoff = { size = "standard-1x", quantity = 0 }
  }

  # Non-sensitive config vars. This app has no DEFAULT_MONGODB live, so the
  # shared base is excluded - the config mirrors live exactly.
  include_base_config_vars = false
  config_vars = {
    JAVA_OPTS        = "-XX:+UseG1GC -Xmx8g -Xms1g"
    PGCLIENTENCODING = "UTF8"
  }

  # Sensitive config vars - values come from the `secrets` map supplied via
  # terraform.tfvars (gitignored). Explicit lookups so a missing key fails
  # loudly at plan time instead of silently dropping a config var.
  sensitive_config_vars = {
    HEROKU_PASSWORD  = var.secrets["HEROKU_PASSWORD"]
    HEROKU_USERNAME  = var.secrets["HEROKU_USERNAME"]
    ORMONGO_DBNAME   = var.secrets["ORMONGO_DBNAME"]
    ORMONGO_PASSWORD = var.secrets["ORMONGO_PASSWORD"]
    ORMONGO_USERNAME = var.secrets["ORMONGO_USERNAME"]
  }
}

# -----------------------------------------------------------------------------
# Addon-injected config vars (NOT managed here)
# -----------------------------------------------------------------------------
# These are set automatically by the attached add-ons, so they are intentionally
# absent from the config above:
#   - ORMONGO_REGION  -> ormongo (billed to worker-rstk-dev)
#   - ORMONGO_RS_URL  -> ormongo (billed to worker-rstk-dev)
#   - ORMONGO_URL     -> ormongo (billed to worker-rstk-dev)

# -----------------------------------------------------------------------------
# Shared add-ons attached to this app (billed to OTHER apps - not managed here)
# -----------------------------------------------------------------------------
#   - ormongo:2-mmap  (billed to worker-rstk-dev)
