# =============================================================================
# worker-test-last-5 - Heroku Application
# =============================================================================
# Part of the "worker" pipeline, "staging" stage.
# Mirrors the live Heroku app. Shared logic and common defaults live in the
# rstk-app module; only this app's specifics are set below.
#
# Generated by tools/codify_app.py - safe to edit by hand afterwards.
# =============================================================================

module "app" {
  source = "../../../../modules/rstk-app"

  app_name       = "worker-test-last-5"
  pipeline_name  = "worker"
  pipeline_stage = "staging"

  # No GitHub integration is configured on this app (github_repo stays null,
  # which skips the Kolkrabbi wiring in the module).

  # Add-ons owned by this app
  addons = {
    papertrail = "papertrail:choklad"
  }

  # Dyno formation (live values)
  formations = {
    worker = { size = "standard-2x", quantity = 1 }
  }

  # Non-sensitive config vars. DEFAULT_MONGODB=ORMONGO comes from the module base.
  config_vars = {
    ARAGING_APP_NAME                          = "finreport-rstk-test"
    ARAGING_ONEOFF_DYNO_TYPE                  = "performance-l"
    ARAGING_PROCESS_NAME                      = "newoneoff"
    MRP_APP_NAME                              = "mrp-rstk-test"
    MRP_ONEOFF_DYNO_TYPE                      = "performance-l"
    MRP_PROCESS_NAME                          = "myworker"
    QUEUE_NAME                                = "LAST-5"
    RF_APP_NAME                               = "rootf-test-last-5"
    RF_ONEOFF_DYNO_TYPE                       = "standard-2x"
    RF_PROCFILE_PROCESS_NAME                  = "rfworker"
    SFORCE_NAMESPACE                          = "DOX__"
    STDCOSTS_APP_NAME                         = "stdcosts-test"
    STDCOSTS_COSTROLLUP_ONEOFF_DYNO_TYPE      = "performance-l"
    STDCOSTS_CSSIMSTDMOVE_ONEOFF_DYNO_TYPE    = "performance-l"
    STDCOSTS_ICSETMTLSIMCOST_ONEOFF_DYNO_TYPE = "standard-2x"
    STDCOSTS_ONEOFF_DYNO_TYPE                 = "performance-l"
    STDCOSTS_POSETMTLCOST_ONEOFF_DYNO_TYPE    = "standard-2x"
    STDCOSTS_PROCESS_NAME                     = "oneoff"
    supportedLocale                           = "de_DE,de_AT,sv_SE,de_DE,en_DE,de_EN,en_NL,fr_FR,pl_PL,da_DK"
  }

  # Sensitive config vars - values come from the `secrets` map supplied via
  # terraform.tfvars (gitignored). Explicit lookups so a missing key fails
  # loudly at plan time instead of silently dropping a config var.
  sensitive_config_vars = {
    API_USN              = var.secrets["API_USN"]
    API_USNKY            = var.secrets["API_USNKY"]
    CLOUDAMQP_APIKEY     = var.secrets["CLOUDAMQP_APIKEY"]
    CLOUDAMQP_URL        = var.secrets["CLOUDAMQP_URL"]
    HEROKU_PASSWORD      = var.secrets["HEROKU_PASSWORD"]
    HEROKU_USERNAME      = var.secrets["HEROKU_USERNAME"]
    ORMONGO_DBNAME       = var.secrets["ORMONGO_DBNAME"]
    ORMONGO_PASSWORD     = var.secrets["ORMONGO_PASSWORD"]
    ORMONGO_USERNAME     = var.secrets["ORMONGO_USERNAME"]
    RSTK_KEY             = var.secrets["RSTK_KEY"]
    SFORCE_CLIENT_KEY    = var.secrets["SFORCE_CLIENT_KEY"]
    SFORCE_CLIENT_SECRET = var.secrets["SFORCE_CLIENT_SECRET"]
  }
}

# -----------------------------------------------------------------------------
# Addon-injected config vars (NOT managed here)
# -----------------------------------------------------------------------------
# These are set automatically by the attached add-ons, so they are intentionally
# absent from the config above:
#   - ORMONGO_REGION  -> ormongo (billed to worker-rstk-test)
#   - ORMONGO_RS_URL  -> ormongo (billed to worker-rstk-test)
#   - ORMONGO_URL     -> ormongo (billed to worker-rstk-test)

# -----------------------------------------------------------------------------
# Shared add-ons attached to this app (billed to OTHER apps - not managed here)
# -----------------------------------------------------------------------------
#   - ormongo:2-mmap  (billed to worker-rstk-test)
