# =============================================================================
# worker-sb-curr - Heroku Application
# =============================================================================
# Part of the "worker" pipeline, "staging" stage.
# Mirrors the live Heroku app. Shared logic and common defaults live in the
# rstk-app module; only this app's specifics are set below.
#
# Generated by tools/codify_app.py - safe to edit by hand afterwards.
# =============================================================================

module "app" {
  source = "../../../../modules/rstk-app"

  app_name       = "worker-sb-curr"
  pipeline_name  = "worker"
  pipeline_stage = "staging"
  stack          = "heroku-22" # differs from the module default

  # No GitHub integration is configured on this app (github_repo stays null,
  # which skips the Kolkrabbi wiring in the module).

  # This app owns no add-ons
  addons = {}

  # No dyno formation exists on this app
  formations = {}

  # Non-sensitive config vars.
  # NOTE: this app has no DEFAULT_MONGODB set live; the module base adds
  # DEFAULT_MONGODB=ORMONGO on first apply.
  config_vars = {

  }

  # Sensitive config vars - values come from the `secrets` map supplied via
  # terraform.tfvars (gitignored). Explicit lookups so a missing key fails
  # loudly at plan time instead of silently dropping a config var.
  sensitive_config_vars = {

  }
}
