# =============================================================================
# rootf-test - Heroku Application
# =============================================================================
# Part of the "rootforms" pipeline, "staging" stage.
# Mirrors the live Heroku app. Shared logic and common defaults live in the
# rstk-app module; only this app's specifics are set below.
#
# Generated by tools/codify_app.py - safe to edit by hand afterwards.
# =============================================================================

module "app" {
  source = "../../../../modules/rstk-app"

  app_name       = "rootf-test"
  pipeline_name  = "rootforms"
  pipeline_stage = "staging"

  # GitHub integration (live values)
  github_repo   = "rootstockmfg/hkrdocs"
  deploy_branch = "qa-build"
  auto_deploy   = false
  wait_for_ci   = false

  # Add-ons owned by this app
  addons = {
    papertrail = "papertrail:choklad"
  }

  # Dyno formation (live values)
  formations = {
    rfworker = { size = "standard-1x", quantity = 0 }
  }

  # Non-sensitive config vars. DEFAULT_MONGODB=ORMONGO comes from the module base.
  config_vars = {
    LOG_LEVEL           = "DEBUG"
    SFORCE_NAMESPACE    = "DOX__"
    SFORCE_REDIRECT_URL = "https://web-rstk-test.herokuapp.com/sf/oauth/callback"
  }

  # Sensitive config vars - values come from the `secrets` map supplied via
  # terraform.tfvars (gitignored). Explicit lookups so a missing key fails
  # loudly at plan time instead of silently dropping a config var.
  sensitive_config_vars = {
    ORMONGO_DBNAME       = var.secrets["ORMONGO_DBNAME"]
    ORMONGO_PASSWORD     = var.secrets["ORMONGO_PASSWORD"]
    ORMONGO_USERNAME     = var.secrets["ORMONGO_USERNAME"]
    SFORCE_CLIENT_KEY    = var.secrets["SFORCE_CLIENT_KEY"]
    SFORCE_CLIENT_SECRET = var.secrets["SFORCE_CLIENT_SECRET"]
  }
}

# -----------------------------------------------------------------------------
# Addon-injected config vars (NOT managed here)
# -----------------------------------------------------------------------------
# These are set automatically by the attached add-ons, so they are intentionally
# absent from the config above:
#   - ORMONGO_REGION        -> ormongo (billed to worker-rstk-test)
#   - ORMONGO_RS_URL        -> ormongo (billed to worker-rstk-test)
#   - ORMONGO_URL           -> ormongo (billed to worker-rstk-test)
#   - PAPERTRAIL_API_TOKEN  -> papertrail (owned by this app)

# -----------------------------------------------------------------------------
# Shared add-ons attached to this app (billed to OTHER apps - not managed here)
# -----------------------------------------------------------------------------
#   - ormongo:2-mmap  (billed to worker-rstk-test)
